server:
  port: 8063
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/payment_db
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  Kafka:
    bootstrap-servers:
      - localhost:9092
      - localhost:9093

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

      acks: all
      retries: 10

      properties:
        enable:
          idempotence: true

        delivery:
          timeout:
            ms: 120000

        request:
          timeout:
            ms: 30000